# Generated by Django 4.1.7 on 2023-09-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
