# Generated by Django 4.1.7 on 2023-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_request',
            field=models.CharField(blank=True, choices=[('requested', 'Requested'), ('approved', 'Approved')], max_length=255, null=True),
        ),
    ]
