# Generated by Django 4.1.7 on 2023-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_birthdate_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_picture'),
        ),
    ]
