# Generated by Django 4.1.7 on 2023-09-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_topic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_writer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
