# Generated by Django 4.1.7 on 2023-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=200)),
                ('banner_type', models.CharField(choices=[('slider', 'Slider'), ('newslater', 'Newslatter'), ('promotion', 'Promotion')], max_length=200)),
                ('banner_image', models.ImageField(upload_to='banner')),
            ],
        ),
    ]
