# Generated by Django 4.1.7 on 2023-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnews',
            name='alertNewsSubtitle',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
