# Generated by Django 4.1.7 on 2023-09-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('slider', 'Slider'), ('newslatter', 'Newslatter'), ('promotion', 'Promotion')], max_length=200),
        ),
    ]
