# Generated by Django 4.1.5 on 2023-02-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alertnews_alertnewssubtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='banner')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_subtitle', models.CharField(max_length=200)),
            ],
        ),
    ]
