# Generated by Django 4.1.7 on 2023-09-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_subscribers_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=155)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=1000)),
                ('querie_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
