# Generated by Django 4.1.7 on 2023-03-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bannerslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertNews',
        ),
    ]
