# Generated by Django 4.1.7 on 2023-09-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='querie_status',
            field=models.CharField(choices=[('sent', 'Sent'), ('replyed', 'Replyed')], default='sent', max_length=10),
        ),
    ]
