# Generated by Django 4.1.7 on 2023-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_queries_querie_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='querie_date',
            new_name='query_date',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='querie_status',
        ),
        migrations.AddField(
            model_name='queries',
            name='query_status',
            field=models.CharField(choices=[('recived', 'Recived'), ('replyed', 'Replyed')], default='sent', max_length=10),
        ),
    ]
