# Generated by Django 4.1.7 on 2023-09-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_querie_date_queries_query_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='query_status',
            field=models.CharField(choices=[('recived', 'Recived'), ('replyed', 'Replyed')], default='recived', max_length=10),
        ),
    ]
