# Generated by Django 4.1.7 on 2023-09-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_message_queries_query_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
