# Generated by Django 4.1.7 on 2023-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_banner', models.ImageField(upload_to='slider')),
                ('slider_offer_title', models.CharField(max_length=155)),
                ('slider_offer', models.CharField(max_length=155)),
                ('slider_offer_description', models.CharField(max_length=155)),
                ('slider_offer_starting_price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
