# Generated by Django 4.1.7 on 2023-09-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_reviews_review_date'),
        ('home', '0010_home_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='Banner')),
                ('banner_title', models.CharField(max_length=155)),
                ('banner_offer', models.CharField(max_length=155)),
                ('banner_product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_product_category', to='products.category')),
            ],
        ),
    ]
