# Generated by Django 4.1.7 on 2023-09-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20230921_1947'),
        ('home', '0011_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_banner', models.ImageField(upload_to='Event')),
                ('event_title', models.CharField(max_length=155)),
                ('event_offer_title', models.CharField(max_length=155)),
                ('event_offer', models.CharField(max_length=155)),
                ('event_product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_product_category', to='products.subcategory')),
            ],
        ),
    ]
