# Generated by Django 4.1.7 on 2023-09-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
