# Generated by Django 4.1.7 on 2023-09-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
