# Generated by Django 4.1.7 on 2023-09-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20230921_1947'),
        ('home', '0015_feedback_is_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_slider',
            name='slider_product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_product_category', to='products.category'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_offer',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_offer',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_offer_title',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='home_slider',
            name='slider_offer',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='home_slider',
            name='slider_offer_description',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='home_slider',
            name='slider_offer_starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='home_slider',
            name='slider_offer_title',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
