# Generated by Django 4.1.7 on 2023-09-27 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20230921_1947'),
        ('home', '0018_alter_home_slider_slider_offer_starting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal_of_the_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_of_the_day_product', to='products.product')),
            ],
        ),
    ]
