# Generated by Django 4.1.7 on 2023-09-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_deal_of_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal_of_the_day',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
