# Generated by Django 4.1.7 on 2023-09-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='RqJ3bHzYQR', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
