<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-09-27 13:51
=======
# Generated by Django 4.1.7 on 2023-09-26 15:26
>>>>>>> 9800a9632cd573b32c3e0190a1ad668f76b60153

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('order', '0002_paymentgatewaysettings_alter_order_order_id'),
=======
        ('order', '0002_alter_order_order_id'),
>>>>>>> 9800a9632cd573b32c3e0190a1ad668f76b60153
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
<<<<<<< HEAD
            field=models.CharField(default='6Kzfpin1sL', editable=False, max_length=10, unique=True),
=======
            field=models.CharField(default='A32lXuiHgh', editable=False, max_length=10, unique=True),
>>>>>>> 9800a9632cd573b32c3e0190a1ad668f76b60153
        ),
    ]
