<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-09-27 14:14
=======
# Generated by Django 4.1.7 on 2023-09-27 07:02
>>>>>>> 9800a9632cd573b32c3e0190a1ad668f76b60153

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
<<<<<<< HEAD
            field=models.CharField(default='P2KWPLDTSN', editable=False, max_length=10, unique=True),
=======
            field=models.CharField(default='l1Xz1cVaPP', editable=False, max_length=10, unique=True),
>>>>>>> 9800a9632cd573b32c3e0190a1ad668f76b60153
        ),
    ]
