# Generated by Django 4.2.5 on 2023-09-30 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '2. Categories',
            },
        ),
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '1. Main Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product')),
                ('product_brand', models.CharField(default='No Brand', max_length=100)),
                ('product_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('product_description', models.TextField()),
                ('product_quantity', models.IntegerField(null=True)),
                ('product_sold_quantity', models.IntegerField(default=0)),
                ('product_location', models.CharField(max_length=100)),
                ('product_featured', models.BooleanField(default=False)),
                ('product_warrenty', models.BooleanField(null=True)),
                ('product_cash_payment', models.BooleanField(null=True)),
                ('product_online_payment', models.BooleanField(null=True)),
                ('product_return', models.BooleanField(null=True)),
                ('product_added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_stock_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Products',
                'ordering': ['-product_added_date'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category')),
            ],
            options={
                'verbose_name_plural': '3. Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Product_Reviews_and_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=255)),
                ('review_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_to', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '5. Product Review And Rating',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='products.main_category'),
        ),
    ]
