# Generated by Django 4.1.7 on 2023-09-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '3. Products'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '2. Sub Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
    ]
