# Generated by Django 4.1.7 on 2023-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='roduct_flash_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
