# Generated by Django 4.1.7 on 2023-09-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '1. Main Category',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_added_date'], 'verbose_name_plural': '4. Products'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '3. Sub Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='products.main_category'),
        ),
    ]
