# Generated by Django 4.1.7 on 2023-09-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_cash_payment',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_online_payment',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_return',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_warrenty',
            field=models.BooleanField(null=True),
        ),
    ]
