# Generated by Django 4.1.7 on 2023-02-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tergeted_buyer',
            field=models.CharField(choices=[('Uni-sex', 'Male & Female'), ('Male', 'Only Male'), ('Female', 'Only Female'), ('Baby', 'Only Baby')], default='Uni-sex', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='product'),
        ),
    ]
