# Generated by Django 4.1.7 on 2023-09-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_added_date'], 'verbose_name_plural': '3. Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_sold_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
