# Generated by Django 4.1.7 on 2023-10-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_roduct_flash_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='roduct_flash_expiry',
            new_name='product_flash_expiry',
        ),
    ]
