# Generated by Django 4.1.7 on 2023-03-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_added_date_product_tergeted_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tergeted_buyer',
            field=models.CharField(choices=[('Male & Female', 'Uni-sex'), ('Only Male', 'Male'), ('Only Female', 'Female'), ('Only Kids', 'Kids')], default='Uni-sex', max_length=50),
        ),
    ]
