# Generated by Django 4.1.7 on 2023-09-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_reviews',
            options={'verbose_name_plural': '5. ProductReview'},
        ),
    ]
