# Generated by Django 4.2.6 on 2026-01-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_flash_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='assets/images/default_product_image.png', upload_to='products/'),
        ),
    ]
