# Generated by Django 4.1.7 on 2023-03-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_tergeted_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tergeted_buyer',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
