# Generated by Django 4.1.7 on 2023-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_reviews_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_featured',
            field=models.BooleanField(default=False),
        ),
    ]
