# Generated by Django 4.1.7 on 2023-09-20 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_product_reviews_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Reviews_and_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=255)),
                ('review_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_to', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '5. Product Review And Rating',
            },
        ),
        migrations.DeleteModel(
            name='product_reviews',
        ),
    ]
