# Generated by Django 4.1.7 on 2023-03-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ({'-added_date'},)},
        ),
    ]
