# Generated by Django 4.1.7 on 2023-09-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_featured'),
        ('products', '0007_product_reviews_and_rating_delete_product_reviews'),
    ]

    operations = [
    ]
