# Generated by Django 4.1.7 on 2023-03-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-added_date']},
        ),
    ]
