# Generated by Django 4.1.7 on 2023-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order_orderitem_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
